### ISSUE TITLE
Add Keynote speaker

### ISSUE THREAD

**Issue by ccwang002** [pycontw/APAC2015WebContent#11]

**Comment by ccwang002** [comment]
Yu De Lin is working on this.

**Comment by 0xyd** [comment]
How to do the Pull Request? I am YuDe Lin.

**Comment by ccwang002** [comment]
Hi have you ever used "fork" before?
1. fork this project
2. update your change; commit it to your forked branch
3. after you push your updated branch, you will see a pull request option on your github repo page.

See github's guide for more info. https://guides.github.com/activities/forking/ or https://help.github.com/articles/fork-a-repo/

**Comment by ccwang002** [comment]
If this is difficult for you, you can send me your changes in text.

**Comment by 0xyd** [comment]
Basically, I will upload the content with the old format (2014 WebContent Style) you give me before. Is that Okay?

**Comment by ccwang002** [comment]
yap. That's good.
