### ISSUE TITLE
無法編輯頁面內容

### ISSUE THREAD

**Issue by lucemia** [pycontw/APAC2015WebContent#15]
無法編輯頁面內容, 點擊頁面時會跳到首頁
https://tw.pycon.org/2015apac/admin/pages/page/

For example 這個頁面會跳到首頁
https://tw.pycon.org/2015apac/admin/pages/page/9/

![screen shot 2015-03-08 at 5 31 45 pm](https://cloud.githubusercontent.com/assets/432851/6545265/4bcc2224-c5b9-11e4-83e3-1db7c46ab1f7.png)

**Comment by ccwang002** [comment]
這個是 bug，可以用自動化的 tool 來更新頁面 https://github.com/ccwang002/pyapac_web_uploader

ps 這個工具不能更改 Draft、Publish 等其他 metadata，所以如果要把草稿發佈的話，現在的做法是把舊的頁面移除再建一個新的

**Comment by lucemia** [comment]
這是 mezzanine 的 bug 嗎？？

**Comment by lucemia** [comment]
謝謝亮亮 ~

**Comment by ccwang002** [comment]
我猜是在 routing 的設定上要調整，去年是 ok 的。昨天 Andy 有說大概還要一段時間才有辦法解好

**Comment by lucemia** [comment]
.... 亮亮你這包要先裝 python 3.4 ...

**Comment by ccwang002** [comment]
恩@@ 我還沒 port 到 2.7，那這樣只能用前台的 EDIT 來改了，登入後訪問 sponsor 那頁會有黃色 EDIT 連結可以點來改內容，選 HTML 直接複製貼上

**Comment by lucemia** [comment]
@ccwang002  了解

@andy 有 source repo 的話我可以幫忙看 bug 發發 pull request ..

**Comment by ccwang002** [comment]
這個問題還在，不過暫時都還有別的解法，先關掉囉
