### ISSUE TITLE
Update the info of registration page

### ISSUE THREAD

**Issue by idlecafe** [pycontw/APAC2015WebContent#27]
the current content is for 2014

**Comment by ccwang002** [comment]
Hi I see you are already working on the Chinese version. Could you help the English version as well?

After you finish, you could send a pull request here, I'll help update the content on web

**Comment by idlecafe** [comment]
Hi, I have committed the change of both Chinese and English versions, and thank for your help~

**Comment by ccwang002** [comment]
close this
