### ISSUE TITLE
Make the committee list as complete as possible

### ISSUE THREAD

**Issue by drakeguan** [pycontw/APAC2015WebContent#32]
In https://tw.pycon.org/2015apac/en/about/, please make the committee list as complete as possible.

What's missing includes:
- Shuen-Huei Guan (官順暉)   Vice Chairperson
- Wen-Chang "Tim" Hsu (許文昌)   Program/ Vice Chairperson /Workshop
- Tsung-Wei Hu (胡祟偉)  Program/Tutorial
- ...

Refer to: https://docs.google.com/spreadsheets/d/15zHRBsLoSnDmf4fhxoJNRwjYY86958sCaR_n9oYtDl4/edit#gid=0

It might be better to put as many contributors as possible :)

PS. Please apply this to the same page in different languages.

**Comment by ccwang002** [comment]
I like the idea to have full committee online (so I can have my name listed and shout 「媽我在這」)

I'll first update missing staff stated here, and put the rest of the idea in a new issue. Working on this!
