### ISSUE TITLE
Make a copy of Code of Conduct from pyconapac2014

### ISSUE THREAD

**Issue by drakeguan** [pycontw/APAC2015WebContent#33]
Currently, the _Code of Conduct_ is referred to pyconapac2014 web page, https://tw.pycon.org/2015apac/en/about/. It would be better to have all pages belong to pyconapac2015 itself. That is, to make this website much self-contained. I suggest to make a copy of CoC and put it under apac2015 website then.

**Comment by drakeguan** [comment]
Actually, I just realized the CoC has a copy already. Please just update the CoC link in https://tw.pycon.org/2015apac/en/about/

**Comment by ccwang002** [comment]
working on this!
