### ISSUE TITLE
Upload the Photos

### ISSUE THREAD

**Issue by 0xyd** [pycontw/APAC2015WebContent#42]
Robert Bradshaw: 
https://drive.google.com/open?id=0B67hU53wKsamYzFqRlZzT2xERGs&authuser=0

Steven G. Johnson:
https://drive.google.com/open?id=0B_a85pX5WSRlaUVwYkc1MUFlcGs&authuser=0

Travis Oliphant:
https://drive.google.com/open?id=0B_a85pX5WSRlQnQ1dmVwUHd0aXc&authuser=0

Van Linberg:
https://drive.google.com/open?id=0B_a85pX5WSRlVmZ5YTExb0JQeWs&authuser=0

**Comment by ccwang002** [comment]
Working on this
