### ISSUE TITLE
日文版註冊頁面翻譯完成，等待上架

### ISSUE THREAD

**Issue by yenchiayi** [pycontw/APAC2015WebContent#47]
文件如下：
https://docs.google.com/document/d/1QqxyeVrogKT2xFY1De-tkRJIU0P5AwVS7NVVbJmHQys/edit?usp=sharing

目前還沒有調 html/css
web組那邊能幫忙嗎？
如果不行請通知我，我找人幫忙做

**Comment by ccwang002** [comment]
沒，你能找到人最好，直接發 pull requedt 吧

**Comment by yenchiayi** [comment]
ok

**Comment by ccwang002** [comment]
I guess this can be closed right?
