### ISSUE TITLE
組長名單誤植

### ISSUE THREAD

**Issue by yenchiayi** [pycontw/APAC2015WebContent#48]
註冊組組長好像誤植了，sosorry （許乃文）
![issue](https://cloud.githubusercontent.com/assets/6258851/7047205/b2c6eeea-de3d-11e4-93d0-47745c9988c7.png)

**Comment by ccwang002** [comment]
有英文名字嗎？，我要三個語言一起改

**Comment by yenchiayi** [comment]
我請本人來回答一下~

**Comment by raspberrypi-tw** [comment]
sosorry （許乃文），感謝

**Comment by ccwang002** [comment]
其實我不是這個意思……我英文頁面幫你寫 Sosorry Hsu 囉
https://tw.pycon.org/2015apac/en/about/
