### ISSUE TITLE
Add about

### ISSUE THREAD

**Issue by ccwang002** [pycontw/APAC2015WebContent#5]
See `en/about.html`

**Comment by Knight-X** [comment]
HI, Kazami
好像權限不夠

**Comment by ccwang002** [comment]
Okay, collaborators are hard to add on Github. So from now on, simply leaving a message to let others know.

**Comment by Knight-X** [comment]
work on this

**Comment by Knight-X** [comment]
1. "For PyCon APAC being held in Taiwan this year, the local PyCon Taiwan 2014 will be halted (or PyCon APAC 2014 is effectively PyCon Taiwan 2014)." is deleted, should add additional information ?
2. where can i find the information of the committee this year ?
