### ISSUE TITLE
update sponsor talk info

### ISSUE THREAD

**Issue by lucemia** [pycontw/APAC2015WebContent#64]
Please help to add sponsor talk to our program page

https://docs.google.com/spreadsheets/d/1WzPrmq6iFKlPQopgncpEDirGFfI04Tb7Che0KtfPWjI/edit#gid=1051274419

**Comment by ccwang002** [comment]
would be best if you could file the pull request directly

**Comment by ccwang002** [comment]
I probably could work on it tomorrow.

**Comment by lucemia** [comment]
1. 我可以直接改線上的版本嗎?
2. sponsor package 頁面線上的有改過 (改過多次了) 可能需要 sync

**Comment by ccwang002** [comment]
也可以，改完了跟我說

**Comment by lucemia** [comment]
https://tw.pycon.org/2015apac/en/program-temp/ updated 了 :)
