### ISSUE TITLE
We have very very long lighting talk

### ISSUE THREAD

**Issue by wdv4758h** [pycontw/APAC2015WebContent#66]
The duration of the lighting talk is "40 mins" !!!

This seems to be an issue in another repo which is private now, so I open the issue here.

![pycon-long-lighting-talk](https://cloud.githubusercontent.com/assets/2716047/7397568/e27acacc-eedb-11e4-92c7-e4d77cb93a0e.png)

**Comment by ccwang002** [comment]
Thanks for your feedback! But this is not the repo that can fix the bug. I'd contact the web team (though they may be busy with the program table right now)
